#!/bin/bash

ver=2009.8.24

opentheory=../..

adir=$opentheory/test/articles/hol-light
if ! test -d $adir ; then echo "$adir not a directory" ; exit 1 ; fi

prog=$opentheory/bin/mlton/opentheory
if ! test -x $prog ; then echo "$prog not an executable" ; exit 1 ; fi

int=$opentheory/test/interpretations/hol-light.int
if ! test -r $int ; then echo "$int not readable" ; exit 1 ; fi

rdir=$opentheory/test/opentheory
if ! test -d $rdir ; then echo "$rdir not a directory" ; exit 1 ; fi

echo '#use "hol.ml";;' | ocaml

if ! test -r bool-def.art ; then echo "bool-def.art not readable" ; exit 1 ; fi
if ! test -r bool-thm.art ; then echo "bool-thm.art not readable" ; exit 1 ; fi
cat bool-def.art bool-thm.art > $adir/bool.art

if ! test -r tactics-thm.art ; then echo "tactics-thm.art not readable" ; exit 1 ; fi
cat tactics-thm.art > $adir/tactics.art

for file in $(ls -tr *.art)
do
    echo
    base=$(basename $file .art)
    pdir=$rdir/packages/hol-light-$base-$ver

    if test -d $pdir
    then
        sum=$base.sum

        if test $file -nt $sum
        then
            echo "compiling" $file

            thy=$base.thy
            echo 'theory { interpret {' > $thy
            cat $int >> $thy
            echo -n '} in article "' >> $thy
            echo -n $file >> $thy
            echo '"; }' >> $thy

            $prog compile --summary-text $sum --article $pdir/$file $thy || exit 1
            ls -l $file
            ls -l $pdir/$file
        else
            echo "skipping" $file "(up to date)"
        fi
    else
        echo -n "skipping "
        ls -l $file
    fi
done

echo

cd $opentheory
make all-generic-theories || exit 1
