#!/bin/bash

prog=bin/mlton/opentheory
if ! test -x $prog ; then echo "$prog not an executable" ; exit 1 ; fi

bumpver=scripts/bump-theory-version
if ! test -x $bumpver ; then echo "$bumpver not an executable" ; exit 1 ; fi

source=../hol-light/opentheory/articles
if ! test -d $source ; then echo "$source not a directory" ; exit 1 ; fi

target=data/theories
if ! test -d $target ; then echo "$target not a directory" ; exit 1 ; fi

for thy in $source/*.thy
do
    base=$(basename $thy .thy)
    tdir=$target/$base
    tthy=$tdir/$base.thy
    tthynew=$tdir/$base.thy.bumping
    tart=$tdir/$base.art
    tartnew=$tdir/$base.art.importing

    if ! test -d $tdir
    then
        mkdir $tdir

        echo "name: $base" > $tthy
        echo "version: 1.0" >> $tthy
        echo "description: $base" >> $tthy
        echo "author: Joe Hurd <joe@gilith.com>" >> $tthy
        echo "license: HOLLight" >> $tthy
        echo -n "source: HOL Light theory segment extracted on " >> $tthy
        date "+%Y-%m-%d" >> $tthy
        echo "show: \"Data.Bool\"" >> $tthy
        echo >> $tthy
        echo "main {" >> $tthy
        echo "  article: \"$base.art\"" >> $tthy
        echo "}" >> $tthy
    fi

    $prog info --preserve-theory --article -o $tartnew $thy || exit 1

    if grep 'Unwanted' $tartnew
    then
        echo "Unwanted symbols found in" $base
        exit 1
    fi

    if test -e $tart
    then
        if ! diff $tart $tartnew >/dev/null
        then
            $bumpver $tthy > $tthynew || exit 1

            mv $tthynew $tthy
            mv $tartnew $tart

            echo "re-imported" $base
        else
            rm $tartnew
        fi
    else
        mv $tartnew $tart

        echo "imported" $base
    fi
done

echo
