#!/usr/bin/perl

# Copyright (c) 2006 Joe Hurd, All Rights Reserved

use strict;
use warnings;
use Pod::Usage;
use Getopt::Std;

use vars qw($opt_h $opt_l $opt_n);

getopts('hln');

if ($opt_h) {
    pod2usage({-exitval => 2,
	       -verbose => 2});
}

# Autoflush STDIN
$|++;

my $opentheory = "bin/mlton/opentheory";
[ -x $opentheory ] or die "upload-theories: $opentheory not an executable";

my $repo = ($opt_l ? "gilith" : "mordor");

my $cmd = "$opentheory --repo $repo update";

(system ($cmd) == 0) or die;

$cmd = "$opentheory --repo $repo list '" . 'Mine & (LaterThanRepo /\ ConsistentWithRepo)' . "'";

my @thys = split (/[[:space:]]+/, `$cmd`);

my $thylist = join (" ", @thys);

if ($thylist eq "") {
  print STDOUT "no theories on $repo need upgrading\n";
}
else {
  $cmd = "$opentheory --repo $repo upload $thylist";

  if ($opt_n) {
    print STDOUT "$cmd\n";
  }
  else {
    (system ($cmd) == 0) or die;
  }
}

__END__

=pod

=head1 NAME

upload-theories - Upload all updated theory packages to the repo

=head1 SYNOPSIS

upload-theories [-h] [-l] [-n]

=head1 ARGUMENTS

The recognized flags are described below:

=over 2

=item B<-h>

Produce this documentation.

=item B<-l>

Upload to the live repo, not the test repo.

=item B<-n>

Do nothing, just echo the command that would be used.

=back

=head1 DESCRIPTION

Uploads all updated theory packages to the OpenTheory repo.

=head1 BUGS

Waiting to rear their ugly heads.

=head1 AUTHORS

Joe Hurd <joe@gilith.com>

=head1 SEE ALSO

Perl(1).

=cut
